IT_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from task_manager.views import register

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", register, name="register"),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task_manager/urls.py
from django.urls import path

from task_manager.views import (index,
                                TaskListView,
                                TaskDetailView,
                                TaskCreateView,
                                TaskUpdateView,
                                TaskDeleteView,
                                task_assign_delete_worker_view,
                                WorkerListView,
                                WorkerDetailView,
                                WorkerUpdateView,
                                PositionListView,
                                PositionDetailView,
                                PositionCreateView,
                                PositionUpdateView,
                                PositionDeleteView,)


urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/assign-worker/",
         task_assign_delete_worker_view,
         name="task-assign-delete-worker"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path("positions/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),

]

app_name = "task_manager"

templates/includes/pagination.html
{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li class="page-item">
        <a href="?page= {{ page_obj.previous_page_number }}" class="page-link">prev</a>
      </li>
    {% endif %}
    <li class="page-item active">
      <span class="page-link">{{ page_obj.number }} of {{ paginator.num_pages }}</span>
    </li>
    {% if page_obj.has_next %}
      <li class="page-item">
        <a href="?page= {{ page_obj.next_page_number }}" class="page-link">next</a>
      </li>
    {% endif %}
  </ul>
{% endif %}

templates/includes/sidebar.html
{% load crispy_forms_filters %}

<ul class="sidebar-nav list-group">
  {% if user.is_authenticated %}
    <li class="list-group-item">User: <a href="{{ user.get_absolute_url }}">{{ user.get_username }}</a></li>
    <li class="list-group-item"><a href="{% url 'logout'%}?next={{request.path}}">Logout</a></li>
  {% else %}
    <li class="list-group-item"><a href="{% url 'login'%}?next={{request.path}}">Login</a></li>
  {% endif %}

  <br>
  {% if page_name != "index" %}
    <form action="" method="get" class="form-inline">
      {{ search_form|crispy }}
    <input class="btn btn-secondary ml-2" type="submit" value="🔍">

    </form>
  {% endif %}
  <li class="list-group-item"><a href="{% url 'task_manager:index' %}">Home</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:task-list' %}">All Tasks</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:worker-list' %}">All Workers</a></li>
  <li class="list-group-item"><a href="{% url 'task_manager:position-list' %}">All Positions</a></li>
</ul>