IT_company_task_manager/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from task_manager.views import register

urlpatterns = [
    path("admin/", admin.site.urls),
    path("register/", register, name="register"),
    path("", include("task_manager.urls", namespace="task_manager")),
    path("accounts/", include("django.contrib.auth.urls")),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

task_manager/urls.py
from django.urls import path

from task_manager.views import (index,
                                TaskListView,
                                TaskDetailView,
                                TaskCreateView,
                                TaskUpdateView,
                                TaskDeleteView,
                                task_assign_delete_worker_view,
                                WorkerListView,
                                WorkerDetailView,
                                WorkerUpdateView,
                                PositionListView,
                                PositionDetailView,
                                PositionCreateView,
                                PositionUpdateView,
                                PositionDeleteView,)


urlpatterns = [
    path("", index, name="index"),
    path("tasks/", TaskListView.as_view(), name="task-list"),
    path("tasks/<int:pk>/", TaskDetailView.as_view(), name="task-detail"),
    path("tasks/<int:pk>/update/", TaskUpdateView.as_view(), name="task-update"),
    path("tasks/<int:pk>/delete/", TaskDeleteView.as_view(), name="task-delete"),
    path("tasks/create/", TaskCreateView.as_view(), name="task-create"),
    path("tasks/<int:pk>/assign-worker/",
         task_assign_delete_worker_view,
         name="task-assign-delete-worker"),
    path("workers/", WorkerListView.as_view(), name="worker-list"),
    path("workers/<int:pk>/", WorkerDetailView.as_view(), name="worker-detail"),
    path("workers/<int:pk>/update/", WorkerUpdateView.as_view(), name="worker-update"),
    path("positions/", PositionListView.as_view(), name="position-list"),
    path("positions/<int:pk>/", PositionDetailView.as_view(), name="position-detail"),
    path("positions/create/", PositionCreateView.as_view(), name="position-create"),
    path("positions/<int:pk>/update/", PositionUpdateView.as_view(), name="position-update"),
    path("positions/<int:pk>/delete/", PositionDeleteView.as_view(), name="position-delete"),

]

app_name = "task_manager"

task_manager/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse


class TaskType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return self.name


class Position(models.Model):
    name = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return f"{self.name}"


class Worker(AbstractUser):
    position = models.ForeignKey(Position, on_delete=models.CASCADE)

    class Meta:
        verbose_name = "worker"
        verbose_name_plural = "workers"

    def __str__(self):
        return f"{self.first_name} {self.last_name}: {self.position.name}"

    def get_absolute_url(self):
        return reverse("task_manager:worker-detail", kwargs={"pk": self.pk})


class Task(models.Model):
    PRIORITY_CHOICES = [
        ("critical", "Critical"),
        ("urgent", "Urgent"),
        ("asap", "ASAP (As Soon As Possible)"),
        ("medium", "Medium"),
    ]

    name = models.CharField(max_length=255)
    description = models.TextField()
    deadline = models.DateTimeField()
    is_completed = models.BooleanField(default=False)
    priority = models.CharField(
        max_length=30,
        choices=PRIORITY_CHOICES,
        default="medium"
    )
    task_type = models.ForeignKey(TaskType, on_delete=models.CASCADE)
    assignees = models.ManyToManyField(Worker, related_name="tasks")

task_manager/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

from task_manager.models import Task, Position, Worker


class RegisterForm(UserCreationForm):
    class Meta:
        model = Worker
        fields = ("first_name", "last_name", "position", "username", "password1", "password2")


class TaskCreationForm(forms.ModelForm):
    class Meta:
        model = Task
        fields = "__all__"
        widgets = {
            "assignees": forms.CheckboxSelectMultiple(),
            "deadline": forms.DateInput(attrs={"type": "date"}),
        }


class TaskSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )


class WorkerSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by username"
            }
        )
    )


class WorkerUpdateForm(forms.ModelForm):
    class Meta:
        model = Worker
        fields = ("first_name", "last_name", "position", "username")


class PositionCreationForm(forms.ModelForm):
    class Meta:
        model = Position
        fields = "__all__"


class PositionSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(
            attrs={
                "placeholder": "Search by name"
            }
        )
    )

task_manager/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic

from .forms import (TaskCreationForm,
                    TaskSearchForm,
                    WorkerSearchForm,
                    WorkerUpdateForm,
                    PositionCreationForm,
                    PositionSearchForm,
                    RegisterForm)

from .models import Task, Position, Worker


def register(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("task_manager:index")
    else:
        form = RegisterForm()
    return render(request, "registration/register.html", {"form": form})


@login_required
def index(request: HttpRequest) -> HttpResponse:
    """View function for the home page of the site."""
    page_name = "index"
    num_tasks = Task.objects.count()
    num_workers = Worker.objects.count()
    num_positions = Position.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "page_name": page_name,
        "num_tasks": num_tasks,
        "num_workers": num_workers,
        "num_positions": num_positions,
        "num_visits": num_visits + 1,
    }

    return render(request, "task_manager/index.html", context=context)


class TaskListView(LoginRequiredMixin, generic.ListView):
    model = Task
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(TaskListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = TaskSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Task.objects.all()
        form = TaskSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class TaskDetailView(LoginRequiredMixin, generic.DetailView):
    model = Task


class TaskCreateView(LoginRequiredMixin, generic.CreateView):
    model = Task
    form_class = TaskCreationForm
    success_url = reverse_lazy("task_manager:task-list")


class TaskUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Task
    fields = "__all__"
    success_url = reverse_lazy("task_manager:task-list")


class TaskDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Task
    success_url = reverse_lazy("task_manager:task-list")


class WorkerListView(LoginRequiredMixin, generic.ListView):
    model = Worker
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(WorkerListView, self).get_context_data(**kwargs)
        username = self.request.GET.get("username", "")
        context["search_form"] = WorkerSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Worker.objects.all()
        form = WorkerSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class WorkerDetailView(LoginRequiredMixin, generic.DetailView):
    model = Worker


class WorkerUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Worker
    form_class = WorkerUpdateForm
    success_url = reverse_lazy("task_manager:worker-list")


class PositionListView(LoginRequiredMixin, generic.ListView):
    model = Position
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super(PositionListView, self).get_context_data(**kwargs)
        name = self.request.GET.get("name", "")
        context["search_form"] = PositionSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Position.objects.all()
        form = PositionSearchForm(self.request.GET)

        if form.is_valid():
            return queryset.filter(
                name__icontains=form.cleaned_data["name"]
            )
        return queryset


class PositionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Position


class PositionCreateView(LoginRequiredMixin, generic.CreateView):
    model = Position
    form_class = PositionCreationForm
    success_url = reverse_lazy("task_manager:position-list")


class PositionUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Position
    fields = "__all__"
    success_url = reverse_lazy("task_manager:position-list")


class PositionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Position
    success_url = reverse_lazy("task_manager:position-list")


@login_required
def task_assign_delete_worker_view(request: HttpRequest, pk: int) -> HttpResponse:
    if request.user in Task.objects.get(id=pk).assignees.all():
        Task.objects.get(id=pk).assignees.remove(request.user)
    else:
        Task.objects.get(id=pk).assignees.add(request.user)
    return redirect(f"/tasks/{pk}/")

templates/task_manager/index.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>Task Manager</h1>
  <h2>Welcome to Best Task Manager!</h2>

  <p>The Task manager has the following record counts:</p>
  <ul>
    <li><strong>Tasks:</strong> {{ num_tasks }}</li>
    <li><strong>Workers:</strong> {{ num_workers }}</li>
    <li><strong>Positions:</strong> {{ num_positions }}</li>
  </ul>

  <p>You have visited this page
    {{ num_visits }} time{{ num_visits|pluralize }}.
  </p>

{% endblock %}

templates/task_manager/position_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>Are you sure you want to delete position  {{ position.name }}?</h1>

  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.back()"><button type="button" class="btn btn-secondary">Cancel</button></a>
  </form>
{% endblock %}

templates/task_manager/position_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  <h2>
    Position: {{ position.name }}
  </h2>
  <a href="{% url 'task_manager:position-delete' pk=position.id %}" class="btn btn-danger link-to-page">
    Delete
  </a>

  <a href="{% url 'task_manager:position-update' pk=position.id %}" class="btn btn-secondary link-to-page">
    Update
  </a>

  <div class="ml-3">
    <h4>Workers</h4>
    {% for worker in position.worker_set.all %}
        <hr>
        <p><strong>Username: </strong><a href="{{ worker.get_absolute_url }}">{{ worker.username }}</a></p>
    {% empty %}
      <p>No workers!</p>
    {% endfor %}
  </div>
{% endblock %}

templates/task_manager/position_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} position</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/position_list.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>
    Positions
    <a href="{% url 'task_manager:position-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  {% if position_list %}
    <ul>
      {% for position in position_list %}
        <li>
          <a href="{% url "task_manager:position-detail" pk=position.id %} ">{{ position.name }}</a>
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>There are no positions</p>
  {% endif %}
{% endblock %}

templates/task_manager/task_confirm_delete.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>Are you sure you want to delete task?</h1>
  <form action="" method="post">
    {% csrf_token %}
    <input type="submit" value="Yes" class="btn btn-danger">
    <a href="javascript:history.back()"><button type="button" class="btn btn-secondary">Cancel</button></a>
  </form>
{% endblock %}

templates/task_manager/task_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>
    {{ task.name }}
    <a href="{% url 'task_manager:task-delete' pk=task.id %}" class="btn btn-danger link-to-page">
      Delete
    </a>
    <a href="{% url 'task_manager:task-update' pk=task.id %}" class="btn btn-secondary link-to-page">
      Update
   </a>
  </h1>
  <p><strong>Task Type:</strong> {{ task.task_type }}</p>
  <p><strong>Description:</strong> {{ task.description }}</p>
  <p><strong>Deadline:</strong> {{ task.deadline }}</p>
  <p><strong>Status:</strong>
    {% if task.is_completed %}
      Completed
    {% else %}
      In progress
    {% endif %}
  </p>
  <p><strong>Priority:</strong> {{ task.priority }}</p>

  <h2>
    Assignees
    {% if user in task.assignees.all %}
      <a href="{% url 'task_manager:task-assign-delete-worker' pk=task.id %}" class="btn btn-danger link-to-page">
      Delete me from this task
      </a>
    {% else %}
      <a href="{% url 'task_manager:task-assign-delete-worker' pk=task.id %}" class="btn btn-success link-to-page">
      Assign me to this task
      </a>
    {% endif %}
  </h2>
  <hr>
  <ul>
    {% for worker in task.assignees.all %}
      <li><a href="{{ worker.get_absolute_url }}">{{ worker.username }}</a> ({{ worker.first_name }} {{ worker.last_name }})</li>
    {% endfor %}
  </ul>
{% endblock %}

templates/task_manager/task_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>{{ object|yesno:"Update,Create" }} task</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/task_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>
    Task list
    <a href="{% url 'task_manager:task-create' %}" class="btn btn-primary link-to-page">
      Create
    </a>
  </h1>
  {% if task_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Description</th>
        <th>Priority</th>
        <th>Deadline</th>
      </tr>
    {% for task in task_list %}
      <tr>
        <td><a href="{% url "task_manager:task-detail" pk=task.id %} ">{{ task.id }}</a></td>
        <td>{{ task.name }}</td>
        <td>{{ task.description }}</td>
        <td>{{ task.priority }}</td>
        <td>{{ task.deadline }}</td>
      </tr>
    {% endfor %}
    </table>
    {% else %}
    <p>There are no tasks</p>
  {% endif %}
{% endblock %}

templates/task_manager/worker_detail.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>
    Username: {{ worker.username }}
    <a href="{% url 'task_manager:worker-update' pk=worker.id %}" class="btn btn-secondary link-to-page">
      Update
   </a>
  </h1>


  <p><strong>First name:</strong> {{ worker.first_name }}</p>
  <p><strong>Last name:</strong> {{ worker.last_name }}</p>
  <p><strong>Email:</strong> {{ worker.email }}</p>
  <p><strong>Position:</strong> {{ worker.position }}</p>

  <div class="ml-3">
    <h4>Tasks</h4>
    {% if worker.tasks.all %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Name</th>
        <th>Task Type</th>
      </tr>
    {% for task in worker.tasks.all %}
      <tr>
        <td>{{ task.id }}</td>
        <td> {{ task.name }}</td>
        <td>{{ task.task_type.name }}</td>
      </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>No tasks!</p>
  {% endif %}
  </div>
{% endblock %}

templates/task_manager/worker_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

{% block content %}
  <h1>Update worker</h1>
  <form action="" method="post" novalidate>
    {% csrf_token %}
    {{ form|crispy }}
    <input type="submit" value="Submit" class="btn btn-primary">
  </form>
{% endblock %}

templates/task_manager/worker_list.html
{% extends "layouts/base.html" %}

{% block content %}
  <h1>Workers</h1>
  {% if worker_list %}
    <table class="table">
      <tr>
        <th>ID</th>
        <th>Username</th>
        <th>First name</th>
        <th>Last name</th>
        <th>Position</th>
      </tr>
    {% for worker in worker_list %}
      <tr>
        <td>{{ worker.id }}</td>
        <td><a href="{{ worker.get_absolute_url }}">{{ worker.username }} {% if user == worker %} (Me){% endif %}</a></td>
        <td>{{ worker.first_name }}</td>
        <td>{{ worker.last_name }}</td>
        <td>{{ worker.position }}</td>
      </tr>
    {% endfor %}
    </table>
    {% else %}
      <p>There are no workers.</p>
    {% endif %}
{% endblock %}